/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;


import Logic.Scheduler;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import InitSO.TaskManagerFrame;

/**
 *
 * @author Kevin
 */
public class bloquearProcesos extends javax.swing.JFrame {

    /**
     * Creates new form Advanced_Frame
     */
    public bloquearProcesos() {
        initComponents();
        this.setLocationRelativeTo(null);
        checkButton.setContentAreaFilled(false); //to make the content area transparent
        checkButton.setBorderPainted(false); //to make the borders transparent
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proceso = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        errorLoglbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        validCPULbl = new javax.swing.JLabel();
        errorCPULbl = new javax.swing.JLabel();
        cpulbl = new javax.swing.JLabel();
        proceso1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(431, 424));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proceso.setBackground(new java.awt.Color(26, 41, 60));
        proceso.setFont(new java.awt.Font("Bauhaus", 1, 48)); // NOI18N
        proceso.setForeground(new java.awt.Color(153, 153, 153));
        proceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proceso.setToolTipText("");
        proceso.setBorder(null);
        proceso.setCaretColor(new java.awt.Color(51, 51, 51));
        proceso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                procesoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                procesoMouseMoved(evt);
            }
        });
        proceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procesoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                procesoMouseExited(evt);
            }
        });
        proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesoActionPerformed(evt);
            }
        });
        getContentPane().add(proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 360, 60));

        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 60, 60));

        errorLoglbl.setFont(new java.awt.Font("Bauhaus Light", 0, 24)); // NOI18N
        errorLoglbl.setForeground(new java.awt.Color(204, 204, 204));
        errorLoglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLoglbl.setText("Choose process to be blocked:");
        getContentPane().add(errorLoglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 420, 40));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Bauhaus", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Block");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 380, 80));

        validCPULbl.setFont(new java.awt.Font("Bauhaus Light", 0, 24)); // NOI18N
        validCPULbl.setForeground(new java.awt.Color(153, 255, 153));
        validCPULbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(validCPULbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 360, 50));

        errorCPULbl.setFont(new java.awt.Font("Bauhaus Light", 0, 24)); // NOI18N
        errorCPULbl.setForeground(new java.awt.Color(255, 102, 102));
        errorCPULbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(errorCPULbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 360, 50));

        cpulbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpulblKeyPressed(evt);
            }
        });
        getContentPane().add(cpulbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        proceso1.setBackground(new java.awt.Color(26, 41, 60));
        proceso1.setFont(new java.awt.Font("Bauhaus", 1, 48)); // NOI18N
        proceso1.setForeground(new java.awt.Color(153, 153, 153));
        proceso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proceso1.setToolTipText("");
        proceso1.setBorder(null);
        proceso1.setCaretColor(new java.awt.Color(51, 51, 51));
        proceso1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                proceso1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                proceso1MouseMoved(evt);
            }
        });
        proceso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceso1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceso1MouseExited(evt);
            }
        });
        proceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceso1ActionPerformed(evt);
            }
        });
        getContentPane().add(proceso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 360, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpulblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpulblKeyPressed

    }//GEN-LAST:event_cpulblKeyPressed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        int i = 0;
        while (i < Scheduler.procesosActivos.size() && Scheduler.procesosActivos.get(i).processName != proceso.getText()){
            i++;
        }
        if (i < Scheduler.procesosActivos.size()){
            Scheduler.AddBloqueado(Scheduler.procesosActivos.get(i));
            Scheduler.RemoveListo(Scheduler.procesosActivos.get(i));
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private void proceso1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceso1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_proceso1MouseDragged

    private void proceso1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceso1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_proceso1MouseMoved

    private void proceso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceso1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_proceso1MouseClicked

    private void proceso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceso1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_proceso1MouseExited

    private void proceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proceso1ActionPerformed

    private void procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesoActionPerformed

    private void procesoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesoMouseExited

    }//GEN-LAST:event_procesoMouseExited

    private void procesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesoMouseClicked

    }//GEN-LAST:event_procesoMouseClicked

    private void procesoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_procesoMouseMoved

    private void procesoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesoMouseDragged

    }//GEN-LAST:event_procesoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloquearProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloquearProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloquearProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloquearProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloquearProcesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel cpulbl;
    private javax.swing.JLabel errorCPULbl;
    private javax.swing.JLabel errorLoglbl;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField proceso;
    private javax.swing.JTextField proceso1;
    private javax.swing.JLabel validCPULbl;
    // End of variables declaration//GEN-END:variables
}
