/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InitSO;

import Logic.Proceso;
import Logic.Recurso;
import Logic.Scheduler;

/**
 *
 * @author juanp
 */
public class Create_Process extends javax.swing.JFrame {
    Recurso impresora = new Recurso("Impresora");
    Recurso camara = new Recurso("Cámara");
    Recurso parlante = new Recurso("Parlante");
    Recurso microfono = new Recurso("Micrófono");
    public Recurso[] recursosDisponibles = new Recurso[4];

    /**
     * Creates new form Create_Process
     */
    public Create_Process() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        totalTime1 = new javax.swing.JTextField();
        in_outputTime1 = new javax.swing.JTextField();
        in_outputWait1 = new javax.swing.JTextField();
        processName1 = new javax.swing.JTextField();
        recurso1 = new javax.swing.JTextField();
        totalTime2 = new javax.swing.JTextField();
        in_outputTime2 = new javax.swing.JTextField();
        in_outputWait2 = new javax.swing.JTextField();
        processName2 = new javax.swing.JTextField();
        priority2 = new javax.swing.JTextField();
        priority1 = new javax.swing.JTextField();
        recurso2 = new javax.swing.JTextField();
        totalTime3 = new javax.swing.JTextField();
        in_outputTime3 = new javax.swing.JTextField();
        in_outputWait3 = new javax.swing.JTextField();
        processName3 = new javax.swing.JTextField();
        priority3 = new javax.swing.JTextField();
        recurso3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField5.setText("Prioridad");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(22, 63, 78));

        totalTime1.setText("Duración del proceso");
        totalTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime1ActionPerformed(evt);
            }
        });

        in_outputTime1.setText("Tiempo entre interrupciones");
        in_outputTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime1ActionPerformed(evt);
            }
        });

        in_outputWait1.setText("Tiempo de bloqueo");
        in_outputWait1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait1ActionPerformed(evt);
            }
        });

        processName1.setText("Nombre del proceso");
        processName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName1ActionPerformed(evt);
            }
        });

        recurso1.setText("Recurso (ingrese número)");
        recurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso1ActionPerformed(evt);
            }
        });

        totalTime2.setText("Duración del proceso");
        totalTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime2ActionPerformed(evt);
            }
        });

        in_outputTime2.setText("Tiempo entre interrupciones");
        in_outputTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime2ActionPerformed(evt);
            }
        });

        in_outputWait2.setText("Tiempo de bloqueo");
        in_outputWait2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait2ActionPerformed(evt);
            }
        });

        processName2.setText("Nombre del proceso");
        processName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName2ActionPerformed(evt);
            }
        });

        priority2.setText("Prioridad (0-98)");
        priority2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority2ActionPerformed(evt);
            }
        });

        priority1.setText("Prioridad (0-98)");
        priority1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority1ActionPerformed(evt);
            }
        });

        recurso2.setText("Recurso (ingrese número)");
        recurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso2ActionPerformed(evt);
            }
        });

        totalTime3.setText("Duración del proceso");
        totalTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime3ActionPerformed(evt);
            }
        });

        in_outputTime3.setText("Tiempo entre interrupciones");
        in_outputTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime3ActionPerformed(evt);
            }
        });

        in_outputWait3.setText("Tiempo de bloqueo");
        in_outputWait3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait3ActionPerformed(evt);
            }
        });

        processName3.setText("Nombre del proceso");
        processName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName3ActionPerformed(evt);
            }
        });

        priority3.setText("Prioridad (0-98)");
        priority3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority3ActionPerformed(evt);
            }
        });

        recurso3.setText("Recurso (ingrese número)");
        recurso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso3ActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("CREACIÓN DE PROCESOS");

        jLabel3.setText("Recursos: 0-impresora, 1-cámara, 2-parlantes, 3-micrófono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(in_outputTime1)
                            .addComponent(totalTime1)
                            .addComponent(in_outputWait1)
                            .addComponent(processName1)
                            .addComponent(recurso1)
                            .addComponent(priority1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(in_outputTime2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_outputWait2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priority2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recurso2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processName2)
                            .addComponent(totalTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(in_outputTime3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_outputWait3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recurso3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processName3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priority3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(totalTime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(in_outputTime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(in_outputWait3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(processName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(priority3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(recurso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(totalTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(in_outputTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(in_outputWait1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(processName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(priority1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(recurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(in_outputTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(in_outputWait2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priority2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(recurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime1ActionPerformed
     
    }//GEN-LAST:event_totalTime1ActionPerformed

    private void in_outputTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime1ActionPerformed

    private void in_outputWait1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait1ActionPerformed

    private void processName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void recurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso1ActionPerformed

    private void totalTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTime2ActionPerformed

    private void in_outputTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime2ActionPerformed

    private void in_outputWait2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait2ActionPerformed

    private void processName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName2ActionPerformed

    private void priority2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority2ActionPerformed

    private void priority1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority1ActionPerformed

    private void recurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso2ActionPerformed

    private void totalTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTime3ActionPerformed

    private void in_outputTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime3ActionPerformed

    private void in_outputWait3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait3ActionPerformed

    private void processName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName3ActionPerformed

    private void priority3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority3ActionPerformed

    private void recurso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        recursosDisponibles[0] = impresora;
        recursosDisponibles[1] = camara;
        recursosDisponibles[2] = parlante;
        recursosDisponibles[3] = microfono;
        if (!totalTime1.getText().equals("Duración del proceso")){
            Proceso proceso1 = new Proceso(Integer.parseInt(totalTime1.getText()), Integer.parseInt(in_outputTime1.getText()), Integer.parseInt(in_outputWait1.getText()), processName1.getText(), Integer.parseInt(priority1.getText()), recursosDisponibles[Integer.parseInt(recurso1.getText())]);
        }
        if (!totalTime2.getText().equals("Duración del proceso")){
            Proceso proceso2 = new Proceso(Integer.parseInt(totalTime2.getText()), Integer.parseInt(in_outputTime2.getText()), Integer.parseInt(in_outputWait2.getText()), processName2.getText(), Integer.parseInt(priority2.getText()), recursosDisponibles[Integer.parseInt(recurso2.getText())]);
        }
        if (!totalTime3.getText().equals("Duración del proceso")){
            Proceso proceso3 = new Proceso(Integer.parseInt(totalTime3.getText()), Integer.parseInt(in_outputTime3.getText()), Integer.parseInt(in_outputWait3.getText()), processName3.getText(), Integer.parseInt(priority3.getText()), recursosDisponibles[Integer.parseInt(recurso3.getText())]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Process().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in_outputTime1;
    private javax.swing.JTextField in_outputTime2;
    private javax.swing.JTextField in_outputTime3;
    private javax.swing.JTextField in_outputWait1;
    private javax.swing.JTextField in_outputWait2;
    private javax.swing.JTextField in_outputWait3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField priority1;
    private javax.swing.JTextField priority2;
    private javax.swing.JTextField priority3;
    private javax.swing.JTextField processName1;
    private javax.swing.JTextField processName2;
    private javax.swing.JTextField processName3;
    private javax.swing.JTextField recurso1;
    private javax.swing.JTextField recurso2;
    private javax.swing.JTextField recurso3;
    private javax.swing.JTextField totalTime1;
    private javax.swing.JTextField totalTime2;
    private javax.swing.JTextField totalTime3;
    // End of variables declaration//GEN-END:variables
}
