/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InitSO;

import Logic.Proceso;
import Logic.Recurso;
import Logic.Scheduler;

/**
 *
 * @author juanp
 */
public class Create_Process extends javax.swing.JFrame {
    Recurso impresora = new Recurso("Impresora");
    Recurso camara = new Recurso("Cámara");
    Recurso parlante = new Recurso("Parlante");
    Recurso microfono = new Recurso("Micrófono");
    public Recurso[] recursosDisponibles = new Recurso[4];

    /**
     * Creates new form Create_Process
     */
    public Create_Process() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        totalTime1 = new javax.swing.JTextField();
        in_outputTime1 = new javax.swing.JTextField();
        in_outputWait1 = new javax.swing.JTextField();
        processName1 = new javax.swing.JTextField();
        recurso1 = new javax.swing.JTextField();
        totalTime2 = new javax.swing.JTextField();
        in_outputTime2 = new javax.swing.JTextField();
        in_outputWait2 = new javax.swing.JTextField();
        processName2 = new javax.swing.JTextField();
        priority2 = new javax.swing.JTextField();
        priority1 = new javax.swing.JTextField();
        recurso2 = new javax.swing.JTextField();
        totalTime3 = new javax.swing.JTextField();
        in_outputTime3 = new javax.swing.JTextField();
        in_outputWait3 = new javax.swing.JTextField();
        processName3 = new javax.swing.JTextField();
        priority3 = new javax.swing.JTextField();
        recurso3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField5.setText("Prioridad");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(22, 63, 78));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalTime1.setBackground(new java.awt.Color(26, 41, 60));
        totalTime1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        totalTime1.setForeground(new java.awt.Color(255, 255, 255));
        totalTime1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTime1.setText("Duracion del proceso");
        totalTime1.setAlignmentX(0.0F);
        totalTime1.setAlignmentY(0.0F);
        totalTime1.setBorder(null);
        totalTime1.setMargin(new java.awt.Insets(0, 0, 0, 6));
        totalTime1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalTime1MouseClicked(evt);
            }
        });
        totalTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(totalTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, 40));

        in_outputTime1.setBackground(new java.awt.Color(26, 41, 60));
        in_outputTime1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputTime1.setForeground(new java.awt.Color(255, 255, 255));
        in_outputTime1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputTime1.setText("Tiempo entre interrupciones");
        in_outputTime1.setBorder(null);
        in_outputTime1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputTime1MouseClicked(evt);
            }
        });
        in_outputTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, 40));

        in_outputWait1.setBackground(new java.awt.Color(26, 41, 60));
        in_outputWait1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputWait1.setForeground(new java.awt.Color(255, 255, 255));
        in_outputWait1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputWait1.setText("Tiempo de bloqueo");
        in_outputWait1.setBorder(null);
        in_outputWait1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputWait1MouseClicked(evt);
            }
        });
        in_outputWait1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait1ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputWait1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 250, 40));

        processName1.setBackground(new java.awt.Color(26, 41, 60));
        processName1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        processName1.setForeground(new java.awt.Color(255, 255, 255));
        processName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        processName1.setText("Nombre del proceso");
        processName1.setBorder(null);
        processName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processName1MouseClicked(evt);
            }
        });
        processName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName1ActionPerformed(evt);
            }
        });
        getContentPane().add(processName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 250, 40));

        recurso1.setBackground(new java.awt.Color(26, 41, 60));
        recurso1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        recurso1.setForeground(new java.awt.Color(255, 255, 255));
        recurso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recurso1.setText("Recurso (ingrese número)");
        recurso1.setBorder(null);
        recurso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recurso1MouseClicked(evt);
            }
        });
        recurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso1ActionPerformed(evt);
            }
        });
        getContentPane().add(recurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 250, 40));

        totalTime2.setBackground(new java.awt.Color(26, 41, 60));
        totalTime2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        totalTime2.setForeground(new java.awt.Color(255, 255, 255));
        totalTime2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTime2.setText("Duracion del proceso");
        totalTime2.setBorder(null);
        totalTime2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalTime2MouseClicked(evt);
            }
        });
        totalTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime2ActionPerformed(evt);
            }
        });
        getContentPane().add(totalTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 240, 40));

        in_outputTime2.setBackground(new java.awt.Color(26, 41, 60));
        in_outputTime2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputTime2.setForeground(new java.awt.Color(255, 255, 255));
        in_outputTime2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputTime2.setText("Tiempo entre interrupciones");
        in_outputTime2.setBorder(null);
        in_outputTime2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputTime2MouseClicked(evt);
            }
        });
        in_outputTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime2ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 240, 40));

        in_outputWait2.setBackground(new java.awt.Color(26, 41, 60));
        in_outputWait2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputWait2.setForeground(new java.awt.Color(255, 255, 255));
        in_outputWait2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputWait2.setText("Tiempo de bloqueo");
        in_outputWait2.setBorder(null);
        in_outputWait2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputWait2MouseClicked(evt);
            }
        });
        in_outputWait2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait2ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputWait2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 240, 40));

        processName2.setBackground(new java.awt.Color(26, 41, 60));
        processName2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        processName2.setForeground(new java.awt.Color(255, 255, 255));
        processName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        processName2.setText("Nombre del proceso");
        processName2.setBorder(null);
        processName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processName2MouseClicked(evt);
            }
        });
        processName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName2ActionPerformed(evt);
            }
        });
        getContentPane().add(processName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 240, 40));

        priority2.setBackground(new java.awt.Color(26, 41, 60));
        priority2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        priority2.setForeground(new java.awt.Color(255, 255, 255));
        priority2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priority2.setText("Prioridad (0-98)");
        priority2.setBorder(null);
        priority2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priority2MouseClicked(evt);
            }
        });
        priority2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority2ActionPerformed(evt);
            }
        });
        getContentPane().add(priority2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 240, 40));

        priority1.setBackground(new java.awt.Color(26, 41, 60));
        priority1.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        priority1.setForeground(new java.awt.Color(255, 255, 255));
        priority1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priority1.setText("Prioridad (0-98)");
        priority1.setBorder(null);
        priority1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priority1MouseClicked(evt);
            }
        });
        priority1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority1ActionPerformed(evt);
            }
        });
        getContentPane().add(priority1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 250, 40));

        recurso2.setBackground(new java.awt.Color(26, 41, 60));
        recurso2.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        recurso2.setForeground(new java.awt.Color(255, 255, 255));
        recurso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recurso2.setText("Recurso (ingrese número)");
        recurso2.setBorder(null);
        recurso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recurso2MouseClicked(evt);
            }
        });
        recurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso2ActionPerformed(evt);
            }
        });
        getContentPane().add(recurso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 240, 40));

        totalTime3.setBackground(new java.awt.Color(26, 41, 60));
        totalTime3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        totalTime3.setForeground(new java.awt.Color(255, 255, 255));
        totalTime3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTime3.setText("Duracion del proceso");
        totalTime3.setBorder(null);
        totalTime3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalTime3MouseClicked(evt);
            }
        });
        totalTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTime3ActionPerformed(evt);
            }
        });
        getContentPane().add(totalTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 240, 40));

        in_outputTime3.setBackground(new java.awt.Color(26, 41, 60));
        in_outputTime3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputTime3.setForeground(new java.awt.Color(255, 255, 255));
        in_outputTime3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputTime3.setText("Tiempo entre interrupciones");
        in_outputTime3.setBorder(null);
        in_outputTime3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputTime3MouseClicked(evt);
            }
        });
        in_outputTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputTime3ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 240, 40));

        in_outputWait3.setBackground(new java.awt.Color(26, 41, 60));
        in_outputWait3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        in_outputWait3.setForeground(new java.awt.Color(255, 255, 255));
        in_outputWait3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_outputWait3.setText("Tiempo de bloqueo");
        in_outputWait3.setBorder(null);
        in_outputWait3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_outputWait3MouseClicked(evt);
            }
        });
        in_outputWait3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_outputWait3ActionPerformed(evt);
            }
        });
        getContentPane().add(in_outputWait3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 240, 40));

        processName3.setBackground(new java.awt.Color(26, 41, 60));
        processName3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        processName3.setForeground(new java.awt.Color(255, 255, 255));
        processName3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        processName3.setText("Nombre del proceso");
        processName3.setBorder(null);
        processName3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processName3MouseClicked(evt);
            }
        });
        processName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processName3ActionPerformed(evt);
            }
        });
        getContentPane().add(processName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 240, 40));

        priority3.setBackground(new java.awt.Color(26, 41, 60));
        priority3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        priority3.setForeground(new java.awt.Color(255, 255, 255));
        priority3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priority3.setText("Prioridad (0-98)");
        priority3.setBorder(null);
        priority3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priority3MouseClicked(evt);
            }
        });
        priority3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priority3ActionPerformed(evt);
            }
        });
        getContentPane().add(priority3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 240, 40));

        recurso3.setBackground(new java.awt.Color(26, 41, 60));
        recurso3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        recurso3.setForeground(new java.awt.Color(255, 255, 255));
        recurso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recurso3.setText("Recurso (ingrese número)");
        recurso3.setBorder(null);
        recurso3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recurso3MouseClicked(evt);
            }
        });
        recurso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso3ActionPerformed(evt);
            }
        });
        getContentPane().add(recurso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 240, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Documents\\GitHub\\Files\\Images\\addIcon.png")); // NOI18N
        jButton1.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Documents\\GitHub\\Files\\Images\\addPressed.png")); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Documents\\GitHub\\Files\\Images\\addRollover.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 60, 60));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREACIÓN DE PROCESOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 42));

        jLabel3.setFont(new java.awt.Font("BauhausC Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recursos: 0- Impresora, 1- Camara, 2- Parlantes, 3- Microfono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Documents\\GitHub\\Files\\Images\\taskManager.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime1ActionPerformed
     
    }//GEN-LAST:event_totalTime1ActionPerformed

    private void in_outputTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime1ActionPerformed

    private void in_outputWait1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait1ActionPerformed

    private void processName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void recurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso1ActionPerformed

    private void totalTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTime2ActionPerformed

    private void in_outputTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime2ActionPerformed

    private void in_outputWait2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait2ActionPerformed

    private void processName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName2ActionPerformed

    private void priority2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority2ActionPerformed

    private void priority1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority1ActionPerformed

    private void recurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso2ActionPerformed

    private void totalTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTime3ActionPerformed

    private void in_outputTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputTime3ActionPerformed

    private void in_outputWait3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_outputWait3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_outputWait3ActionPerformed

    private void processName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processName3ActionPerformed

    private void priority3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priority3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priority3ActionPerformed

    private void recurso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        recursosDisponibles[0] = impresora;
        recursosDisponibles[1] = camara;
        recursosDisponibles[2] = parlante;
        recursosDisponibles[3] = microfono;
        if (!totalTime1.getText().equals("Duración del proceso")){
            Proceso proceso1 = new Proceso(Integer.parseInt(totalTime1.getText()), Integer.parseInt(in_outputTime1.getText()), Integer.parseInt(in_outputWait1.getText()), processName1.getText(), Integer.parseInt(priority1.getText()), recursosDisponibles[Integer.parseInt(recurso1.getText())]);
        }
        if (!totalTime2.getText().equals("Duración del proceso")){
            Proceso proceso2 = new Proceso(Integer.parseInt(totalTime2.getText()), Integer.parseInt(in_outputTime2.getText()), Integer.parseInt(in_outputWait2.getText()), processName2.getText(), Integer.parseInt(priority2.getText()), recursosDisponibles[Integer.parseInt(recurso2.getText())]);
        }
        if (!totalTime3.getText().equals("Duración del proceso")){
            Proceso proceso3 = new Proceso(Integer.parseInt(totalTime3.getText()), Integer.parseInt(in_outputTime3.getText()), Integer.parseInt(in_outputWait3.getText()), processName3.getText(), Integer.parseInt(priority3.getText()), recursosDisponibles[Integer.parseInt(recurso3.getText())]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalTime1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalTime1MouseClicked
        totalTime1.setText("");
    }//GEN-LAST:event_totalTime1MouseClicked

    private void in_outputTime1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputTime1MouseClicked
        in_outputTime1.setText("");
    }//GEN-LAST:event_in_outputTime1MouseClicked

    private void in_outputWait1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputWait1MouseClicked
        in_outputWait1.setText("");
    }//GEN-LAST:event_in_outputWait1MouseClicked

    private void processName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processName1MouseClicked
        processName1.setText("");
    }//GEN-LAST:event_processName1MouseClicked

    private void priority1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priority1MouseClicked
         priority1.setText("");
    }//GEN-LAST:event_priority1MouseClicked

    private void recurso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recurso1MouseClicked
        recurso1.setText("");
    }//GEN-LAST:event_recurso1MouseClicked

    private void totalTime2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalTime2MouseClicked
         totalTime2.setText("");
    }//GEN-LAST:event_totalTime2MouseClicked

    private void in_outputTime2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputTime2MouseClicked
        in_outputTime2.setText("");
    }//GEN-LAST:event_in_outputTime2MouseClicked

    private void in_outputWait2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputWait2MouseClicked
        in_outputWait2.setText("");
    }//GEN-LAST:event_in_outputWait2MouseClicked

    private void processName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processName2MouseClicked
        processName2.setText("");
    }//GEN-LAST:event_processName2MouseClicked

    private void priority2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priority2MouseClicked
        priority2.setText("");
    }//GEN-LAST:event_priority2MouseClicked

    private void recurso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recurso2MouseClicked
        recurso2.setText("");
    }//GEN-LAST:event_recurso2MouseClicked

    private void totalTime3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalTime3MouseClicked
        totalTime3.setText("");
    }//GEN-LAST:event_totalTime3MouseClicked

    private void in_outputTime3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputTime3MouseClicked
         in_outputTime3.setText("");
    }//GEN-LAST:event_in_outputTime3MouseClicked

    private void in_outputWait3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_outputWait3MouseClicked
       in_outputWait3.setText("");
    }//GEN-LAST:event_in_outputWait3MouseClicked

    private void processName3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processName3MouseClicked
         processName3.setText("");
    }//GEN-LAST:event_processName3MouseClicked

    private void priority3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priority3MouseClicked
        priority3.setText("");
    }//GEN-LAST:event_priority3MouseClicked

    private void recurso3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recurso3MouseClicked
        recurso3.setText("");
    }//GEN-LAST:event_recurso3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Process().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in_outputTime1;
    private javax.swing.JTextField in_outputTime2;
    private javax.swing.JTextField in_outputTime3;
    private javax.swing.JTextField in_outputWait1;
    private javax.swing.JTextField in_outputWait2;
    private javax.swing.JTextField in_outputWait3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField priority1;
    private javax.swing.JTextField priority2;
    private javax.swing.JTextField priority3;
    private javax.swing.JTextField processName1;
    private javax.swing.JTextField processName2;
    private javax.swing.JTextField processName3;
    private javax.swing.JTextField recurso1;
    private javax.swing.JTextField recurso2;
    private javax.swing.JTextField recurso3;
    private javax.swing.JTextField totalTime1;
    private javax.swing.JTextField totalTime2;
    private javax.swing.JTextField totalTime3;
    // End of variables declaration//GEN-END:variables
}
